### ISSUE TITLE
Easy to break into the customer area.

### ISSUE THREAD

**Issue by anselmojunin** [openfactory-ch/whmcs-oath-addon#9]
When configuring 2FA for the client. Once you try to log in, and ask for the 6-digit token, simply click on any of the registered client-side services, which will no longer be requested token (even if it has never been typed).

The token is only requested on the login screen, and no other token is requested (even though you have not typed in the access before).

**Comment by dionysius** [comment]
can confirm on whmcs v7.1, what whmcs version are you using?

**Comment by dionysius** [comment]
I found out something. I need you to confirm my discovery: Does it *not break* when you left "Remember Me" unticked?

Because how I found out, this seems to be the issue:
- This plugin is reverting the login [via hook](https://github.com/openfactory-ch/whmcs-oath-addon/blob/master/modules/addons/oath/hooks.php#L55)
- But when "Remember me" was ticket. WHMCS is adding them back to the session :(

**Comment by dionysius** [comment]
Fix released: https://github.com/openfactory-ch/whmcs-oath-addon/releases/tag/v2.4

Also please join discussion [here](https://forums.whmcs.com/showthread.php?123962-Disable-WHMCSUser-Cookie) about the admin not able to anyhow invalidate any previous autologins.
